### ISSUE TITLE
Keep Getting Crypto error

### ISSUE THREAD

**Issue by sbozek** [cribdragg3r/Alaris#8]
Keep getting "ModuleNotFoundError: No module named 'Crypto'" even tho I have cryptodome installed.  What am I doing wrong here?

**Comment by mrothbart** [comment]
pip3 install -r requirements.txt

or purge your crypto module and reinstall it this way.
Make sure you dont have py2.7 and py3 and using the wrong pip or the wrong path. 

Also stackoverflow has tons of other solutions for this.

**Comment by cribdragg3r** [comment]
Please install all the requirements: `pip3 install -r requirements.txt`
